[build]
builder = "NIXPACKS"
buildCommand = "npm install --prefix leaderboard-server"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
