import { StyleSheet } from 'react-native';
import type { ThemeColors } from './theme';
import { spacing } from './theme';

export default function createCalculatorStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    content: {
      padding: spacing.xl,
      gap: spacing.lg,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      padding: spacing.lg,
      borderWidth: 1,
      borderColor: colors.border,
    },
    title: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '700',
      marginBottom: spacing.md,
    },
    label: {
      color: colors.textSubtle,
      fontSize: 12,
      marginBottom: spacing.xs,
    },
    labelCompact: {
      color: colors.textMuted,
      fontSize: 11,
      marginBottom: 6,
      textAlign: 'center',
      width: '100%',
    },
    input: {
      backgroundColor: colors.surfaceAlt,
      color: colors.text,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: spacing.md,
    },
    levelRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.md,
    },
    levelPill: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    levelPillText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
    },
    tableHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.sm,
    },
    tableRow: {
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      gap: spacing.sm,
    },
    rowTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
    },
    rowDragging: {
      opacity: 0.9,
      backgroundColor: colors.surfaceAlt,
      borderRadius: 12,
      paddingHorizontal: spacing.xs,
    },
    rowBottom: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: spacing.sm,
      paddingLeft: spacing.xs,
      paddingRight: spacing.xs,
    },
    mobileGroup: {
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    markGroup: {
      flex: 0,
      width: 132,
      alignItems: 'flex-start',
    },
    bonusGroup: {
      flex: 1,
      minWidth: 0,
      alignItems: 'center',
    },
    xpGroup: {
      flex: 0,
      width: 56,
      alignItems: 'center',
    },
    cellName: {
      flex: 1,
    },
    stepper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    stepButton: {
      width: 28,
      height: 32,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepButtonDisabled: {
      opacity: 0.4,
    },
    stepButtonText: {
      color: colors.text,
      fontSize: 16,
      lineHeight: 18,
      fontWeight: '700',
    },
    dragHandle: {
      width: 28,
      height: 28,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dragHandleText: {
      color: colors.textMuted,
      fontWeight: '700',
      fontSize: 14,
      lineHeight: 14,
    },
    cellAction: {
      width: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    xpText: {
      color: colors.text,
      fontSize: 12,
      textAlign: 'center',
      minWidth: 40,
      paddingTop: 8,
      lineHeight: 16,
    },
    inputSmall: {
      backgroundColor: colors.surfaceAlt,
      color: colors.text,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      fontSize: 12,
    },
    gradeInput: {
      textAlign: 'center',
      minWidth: 56,
    },
    addRowButton: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 12,
      paddingVertical: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      marginTop: spacing.md,
    },
    addRowText: {
      color: colors.text,
      fontWeight: '600',
    },
    removeText: {
      color: colors.error,
      fontSize: 20,
      fontWeight: '700',
      lineHeight: 20,
    },
    suggestions: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 12,
      paddingVertical: spacing.xs,
      paddingHorizontal: spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: spacing.sm,
    },
    suggestionItem: {
      paddingVertical: 6,
    },
    suggestionText: {
      color: colors.text,
      fontSize: 12,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '600',
    },
    projectsList: {
      gap: 0,
    },
    roadmapSection: {
      marginTop: spacing.lg,
      gap: spacing.sm,
    },
    roadmapSaveRow: {
      flexDirection: 'row',
      gap: spacing.sm,
      alignItems: 'center',
    },
    roadmapInput: {
      flex: 1,
      backgroundColor: colors.surfaceAlt,
      color: colors.text,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
      fontSize: 12,
    },
    roadmapSaveButton: {
      backgroundColor: colors.accent,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 10,
    },
    roadmapSaveText: {
      color: colors.accentText,
      fontSize: 12,
      fontWeight: '700',
    },
    roadmapList: {
      gap: spacing.xs,
    },
    roadmapItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: spacing.xs,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    roadmapName: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '600',
      flex: 1,
    },
    roadmapRenameInput: {
      backgroundColor: colors.surfaceAlt,
      color: colors.text,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 8,
      paddingVertical: 4,
      fontSize: 12,
      minWidth: 120,
      maxWidth: 180,
    },
    roadmapMeta: {
      color: colors.textMuted,
      fontSize: 11,
    },
    roadmapActions: {
      flexDirection: 'row',
      gap: spacing.sm,
      alignItems: 'center',
      marginLeft: spacing.sm,
    },
    roadmapActionText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '600',
    },
    roadmapOverrideButton: {
      backgroundColor: '#facc15',
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    roadmapOverrideText: {
      color: '#1f2937',
      fontSize: 12,
      fontWeight: '700',
    },
    roadmapDeleteText: {
      color: colors.error,
      fontSize: 12,
      fontWeight: '600',
    },
    errorText: {
      color: colors.error,
      fontSize: 12,
    },
    row: {
      flexDirection: 'row',
      gap: spacing.md,
      alignItems: 'center',
    },
    checkbox: {
      width: 20,
      height: 20,
      marginTop: 6,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceAlt,
    },
    checkboxActive: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    checkboxText: {
      color: colors.accentText,
      fontWeight: '700',
    },
    button: {
      backgroundColor: colors.accent,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: 'center',
      marginTop: spacing.md,
    },
    buttonText: {
      color: colors.accentText,
      fontWeight: '700',
    },
    resultRow: {
      marginTop: spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    resultMeta: {
      flex: 1,
    },
    result: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '700',
    },
    resultHint: {
      marginTop: 2,
      color: colors.textMuted,
      fontSize: 12,
    },
    progressButton: {
      backgroundColor: colors.surfaceAlt,
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    progressButtonText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
    },
    hint: {
      color: colors.textMuted,
      marginTop: spacing.xs,
    },
  });
}
